PygitalToolWeb/Controllers/AdminPlatform/api/BackofficeController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.AdminPlatform;

namespace PhygitalTool.Web.Controllers.AdminPlatform.api;
[ApiController]
[Route("api/[controller]")]
public class BackofficeController : Controller
{
    private readonly IAdminPlatformManager _adminPlatformManager;

    public BackofficeController(IAdminPlatformManager adminPlatformManager)
    {
        _adminPlatformManager = adminPlatformManager;
    }
    [HttpGet("GetBackoffices")]
    public IActionResult GetBackoffices()
    {
        
        IEnumerable <Domain.Platform.BackOffice> backoffices = _adminPlatformManager.GetBackoffices();
        
        if (!backoffices.Any())
        {
            return NoContent();
        }
        return Ok(backoffices);
    }
}

PygitalToolWeb/Controllers/BackOffice/BackOfficeController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class BackOfficeController : Controller
{
    private readonly IBackOfficeManager _backOfficeManager;

    public BackOfficeController(IBackOfficeManager backOfficeManager)
    {
        _backOfficeManager = backOfficeManager;
    }

    // GET
    [Authorize(Roles = "Manager")]
    public IActionResult Index()
    {
        string managerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        Domain.Platform.BackOffice backOffice = _backOfficeManager.GetBackOfficeForManager(managerId);
        return View("ProjectsView", backOffice);
    }
    
}

PygitalToolWeb/Controllers/BackOffice/FlowCreationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.Projects;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class FlowCreationController : Controller
{
    private readonly IProjectManager _projectManager;

    public FlowCreationController(IProjectManager projectManager)
    {
        _projectManager = projectManager;
    }

    // GET
    [Authorize(Roles = "Manager")]
    public IActionResult Index(int subThemeId)
    {
        SubTheme subTheme = _projectManager.GetSubThemeWithFlows(subThemeId);
        return View("~/Views/BackOffice/FlowsView.cshtml", subTheme);
    }
}

PygitalToolWeb/Controllers/BackOffice/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.Projects;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class ProjectsController : Controller

{
    private readonly IProjectManager _projectManager;

    // GET
    public ProjectsController(IProjectManager projectManager)
    {
        _projectManager = projectManager;
    }

    [Authorize(Roles = "Manager")]
    public IActionResult Index(int projectId)
    {
        Project project = _projectManager.GetProjectWithThemes(projectId);
        return View("~/Views/BackOffice/ThemesView.cshtml", project);
    }
}

PygitalToolWeb/Controllers/BackOffice/ShowNotesController.cs
using Microsoft.AspNetCore.Mvc;


namespace PhygitalTool.Web.Controllers.BackOffice;

public class ShowNotesController : Controller
{
    public IActionResult Index()
    {
        return View("~/Views/Supervisors/NotesResults.cshtml");
    }
}

PygitalToolWeb/Controllers/BackOffice/SubThemeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.Projects;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class SubThemeController : Controller
{
    private readonly IProjectManager _projectManager;

    public SubThemeController(IProjectManager projectManager)
    {
        _projectManager = projectManager;
    }

    // GET
    [Authorize(Roles = "Manager")]
    public IActionResult Index(int subThemeId)
    {
        SubTheme subTheme = _projectManager.GetSubTheme(subThemeId);
        return View("~/Views/BackOffice/FlowsView.cshtml", subTheme);
    }
}

PygitalToolWeb/Controllers/BackOffice/SupervisorsController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.DAL.IRepositorys;
using PhygitalTool.Domain.Platform;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class SupervisorsController : Controller
{
    private readonly IRepositoryBackOffice _repositoryBackOffice;

    // GET
    public SupervisorsController(IRepositoryBackOffice repositoryBackOffice)
    {
        _repositoryBackOffice = repositoryBackOffice;
    }

    public IEnumerable<Supervisor> ReadSupervisorWithFlows(string supervisorId)
    {
        var supervisorWithFlows = _repositoryBackOffice.ReadSupervisorWithFlows(supervisorId);

        return supervisorWithFlows != null ? new List<Supervisor> { supervisorWithFlows } : new List<Supervisor>();
    }
}

PygitalToolWeb/Controllers/BackOffice/ThemesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.Projects;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class ThemesController : Controller
{
    private readonly IProjectManager _projectManager;

    public ThemesController(IProjectManager projectManager)
    {
        _projectManager = projectManager;
    }

    // GET
    [Authorize(Roles = "Manager")]
    public IActionResult Index(int themeId)
    {
        MainTheme mainTheme = _projectManager.GetThemeWithSubthemes(themeId);
        return View("~/Views/BackOffice/SubThemesView.cshtml",mainTheme);
    }
    
}

PygitalToolWeb/Controllers/BackOffice/UserFormController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.Users;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class UserFormController : Controller
{
    private readonly IUserManager _userManager;

    public UserFormController(IUserManager userManager)
    {
        _userManager = userManager;
    }
    public IActionResult Index()
    {
        var ideas = _userManager.GetAllIdeasWithUsers();
        return View("~/Views/UserIdea/UserIDeaForm.cshtml",ideas);
    }
}

PygitalToolWeb/Controllers/BackOffice/api/BackOfficeCreationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Web.Models;

namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("api/[controller]")]
public class BackOfficeCreationController : Controller
{
    private readonly IBackOfficeManager _backOfficeManager;
    private readonly UnitOfWork _unitOfWork;

    public BackOfficeCreationController(IBackOfficeManager backOfficeManager, UnitOfWork unitOfWork)
    {
        _backOfficeManager = backOfficeManager;
        _unitOfWork = unitOfWork;
    }

    [Authorize(Roles = "Admin")]
    [HttpPost("AddBackOffice")]
    public IActionResult AddBackOffice(BackOfficeModel backOffice)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            var domainBackOffice = new Domain.Platform.BackOffice
            {
                Name = backOffice.Name,
                AdminPlatformId = backOffice.AdminPlatformId
            };

            _unitOfWork.BeginTransaction();
            _backOfficeManager.AddBackOffice(domainBackOffice);
            _unitOfWork.Commit();

            return NoContent();
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"internal server error: {ex.Message}");
        }
    }

    [Authorize(Roles = "Admin")]
    [HttpDelete("DeleteBackOffice/{backOfficeId}")]
    public IActionResult DeleteBackOffice(int backOfficeId)
    {
        try
        {
            _unitOfWork.BeginTransaction();
            _backOfficeManager.DeleteBackOffice(backOfficeId);
            _unitOfWork.Commit();
            return Ok();
        }
        catch (Exception ex)
        {
            return BadRequest($"Error deleting backoffice: {ex.Message}");
        }
    }

    [Authorize(Roles = "Admin")]
    [HttpGet("GetBackOfficeDetails/{backOfficeId}")]
    public IActionResult GetBackOfficeDetails(int backOfficeId)
    {
        try
        {
            var backOffice = _backOfficeManager.GetBackOffice(backOfficeId);
            if (backOffice == null)
            {
                return NotFound($"BackOffice with ID {backOfficeId} not found.");
            }

            var model = new BackOfficeModel
            {
                Name = backOffice.Name,
                AdminPlatformId = backOffice.AdminPlatformId
            };

            return Ok(model);
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [Authorize(Roles = "Admin")]
    [HttpPut("UpdateBackOffice/{backOfficeId}")]
    public IActionResult UpdateBackOffice(int backOfficeId,  BackOfficeModel backOfficeModel)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            var existingBackOffice = _backOfficeManager.GetBackOffice(backOfficeId);
            if (existingBackOffice == null)
            {
                return NotFound($"BackOffice with ID {backOfficeId} not found.");
            }

            existingBackOffice.Name = backOfficeModel.Name;

            _unitOfWork.BeginTransaction();
            _backOfficeManager.UpdateBackOffice(existingBackOffice);
            _unitOfWork.Commit();

            return Ok();
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }
}

PygitalToolWeb/Controllers/BackOffice/api/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL;
using PhygitalTool.BL.Users;
using PhygitalTool.Domain.FlowPackage;

namespace PhygitalTool.Web.Controllers.BackOffice.api;
[ApiController]
[Route("api/[controller]")]
public class CommentController: ControllerBase
{
    private readonly IUserManager _userManager;
    private readonly UnitOfWork _unitOfWork;

    public CommentController(IUserManager userManager, UnitOfWork unitOfWork)
    {
        _userManager = userManager;
        _unitOfWork = unitOfWork;
    }

    [HttpPost]
    [Authorize(Roles = "User")]
    public IActionResult PostComment(Comment comment)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
      
        _unitOfWork.BeginTransaction();
        _userManager.AddCommentToIdea(comment.Description, comment.UserId, comment.IdeaId);
        _unitOfWork.Commit();

        return NoContent();
    }
}

PygitalToolWeb/Controllers/BackOffice/api/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.Web.Services;

namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("/api/files")]
public class FilesController : ControllerBase
{
    private readonly CloudStorageService _cloudStorageService;

    public FilesController(CloudStorageService cloudStorageService)
    {
        _cloudStorageService = cloudStorageService;
    }

    [HttpPost("uploadFile")]
    public ActionResult UploadFile(IFormFile file)
    {
        using var memoryStream = new MemoryStream();
        file.CopyTo(memoryStream);
        var url = _cloudStorageService.UploadFileToBucket(memoryStream, file.ContentType);
        return Ok(new { url });
    }
    

}

PygitalToolWeb/Controllers/BackOffice/api/GeminiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("api/[controller]")]
public class GeminiController : ControllerBase
{
    private readonly string _apiKey;

    public GeminiController(IConfiguration configuration)
    {
        _apiKey = configuration["Keys:gemini_api_key"];
    }

    [HttpGet("gemini-api-key")]
    [Authorize]
    public IActionResult GetGeminiApiKey()
    {
        return Ok(new { apiKey = _apiKey });
    }
}

PygitalToolWeb/Controllers/BackOffice/api/IdeasController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL;
using PhygitalTool.BL.Users;
using PhygitalTool.Domain.FlowPackage;

namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("api/[controller]")]
public class IdeasController : ControllerBase
{
    private readonly IUserManager _userManager;
    private readonly UnitOfWork _unitOfWork;

    public IdeasController(IUserManager userManager, UnitOfWork unitOfWork)
    {
        _userManager = userManager;
        _unitOfWork = unitOfWork;
    }

    // POST: api/Ideas
    [HttpPost]
    public IActionResult PostIdea(Idea idea)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        _unitOfWork.BeginTransaction();
        _userManager.AddIdeas(idea.Title, idea.Description, idea.UserId);
        _unitOfWork.Commit();

        return NoContent();
    }

    [HttpPost("Like/{ideaId}")]
    public IActionResult LikeIdea(int ideaId)
    {
        try
        {
            _unitOfWork.BeginTransaction();
            var likesAmount = _userManager.UpdateLikeIdea(ideaId);
            _unitOfWork.Commit();
            return Ok(new { likes = likesAmount });
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }
}

PygitalToolWeb/Controllers/BackOffice/api/NotesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.FlowPackage;
using PhygitalTool.Web.Models;


namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("api/[controller]")]
public class NotesController : Controller
{
    private readonly IProjectManager _projectManager;
    private readonly UnitOfWork _unitOfWork;

    public NotesController(IProjectManager projectManager, UnitOfWork unitOfWork)
    {
        _projectManager = projectManager;
        _unitOfWork = unitOfWork;
    }
    
    [HttpPost("PostNote")]
    public IActionResult PostNote(NoteModel note)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        } 
        
        _unitOfWork.BeginTransaction();
        _projectManager.AddNote(note.QuestionId, note.Description);
        _unitOfWork.Commit();
        
        return NoContent();
    }




    [Authorize(Roles = "Manager,Supervisor")]
    [HttpGet("GetNotes")]
    public IActionResult GetNotes()
    {
        var notes = _projectManager.GetNotes();

        if (!notes.Any())
        {
            return NoContent();
        }

        return Ok(notes);
    }

    public IActionResult Index()
    {
        return View("~/Views/Supervisors/NotesView.cshtml");
    }
}

PygitalToolWeb/Controllers/BackOffice/api/ResultsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.BL.Flows;
using PhygitalTool.Domain.Projects;
using PhygitalTool.Web.Models;
using Project = PhygitalTool.Domain.Projects.Project;

namespace PhygitalTool.Web.Controllers.BackOffice.api;

[ApiController]
[Route("api/[controller]")]
public class ResultsController : Controller
{
    private readonly IProjectManager _projectManager;
    private readonly IFlowManager _flowManager;

    public ResultsController(IProjectManager iProjectManager, IFlowManager iFlowManager)
    {
        _projectManager = iProjectManager;
        _flowManager = iFlowManager;
    }

    [Authorize(Roles = "Manager")]
    [HttpGet("GetProjectWithData/{projectId}")]
    public IActionResult GetProjectWithData(int projectId)
    {
        var userInputs = _flowManager.GetAllUserInputsForProject(projectId);
        if (userInputs == null)
        {
            return NotFound($"No user inputs found for project with ID {projectId}.");
        }

        var response = new ProjectDataResponseModel
        {
            UserInputs = userInputs
        };

        return Ok(response);
    }

    [Authorize(Roles = "Manager")]
    [HttpGet("GetAllAnswersWithQuestions")]
    public IActionResult GetAllAnswersWithQuestions()
    {
        try
        {
            var answersWithQuestions = _flowManager.GetAllAnswersWithQuestions();

            if (answersWithQuestions == null)
            {
                return NotFound("No answers with questions found.");
            }

            return Ok(answersWithQuestions);
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [Authorize(Roles = "Manager")]
    [HttpGet("GetProjectFromFlowId/{flowId}")]
    public IActionResult GetProjectFromFlowId(int flowId)
    {
        try
        {
            ProjectDTO projectFromFlow = _flowManager.GetProjectFromFlow(flowId);

            if (projectFromFlow == null)
            {
                return NotFound("No answers with questions found.");
            }

            return Ok(projectFromFlow);
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    public IActionResult Index(int projectId)
    {
        Project project = _projectManager.GetProjectWithThemes(projectId);
        return View("~/Views/BackOffice/ResultsView.cshtml", project);
    }
}

PygitalToolWeb/Views/BackOffice/FlowsView.cshtml
@model PhygitalTool.Domain.Projects.SubTheme

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<body class="animated-background">

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 sidebar">
            <div class="text-center mt-4">
                @foreach (var manager in Model.MainTheme.Project.BackOffice.Managers)
                {
                    if (manager.UserName == User.Identity?.Name)
                    {
                        <img src="@manager.ImageUrl" alt="Profile Picture" class="rounded-circle img-fluid">
                        <h5>@manager.UserName</h5>
                        <p>@Model.MainTheme.Project.BackOffice.Name</p>
                    }
                }
            </div>
            <div class="nav flex-column">
                <a class="nav-link active" asp-area="" asp-controller="FlowCreation"
                   asp-action="index" asp-route-subThemeId="@Model.SubThemeId">
                    Flows <span class="badge badge-primary ">@Model.Flows.Count</span>
                </a>
                <a class="nav-link" asp-area="" asp-controller="BackOffice"
                   asp-action="index">
                    Projecten
                </a>
                <a class="nav-link"
                   asp-controller="SubTheme"
                   asp-action="ShowSubThemeSelection"
                   asp-route-backOfficeId="@Model.MainTheme.Project.BackOffice.BackOfficeId">
                    Kiosk Modus
                </a>
                <a class="nav-link" asp-area="" asp-controller="Themes"
                   asp-action="index"
                   asp-route-themeId="@Model.MainThemeId">
                    Terug
                </a>
            </div>
        </div>
        <!-- Flows-->
        <div class="col-md-9 main-container" id="flow-container">
            <h2 class="mt-4">Flows</h2>
            <div class="row">

                @foreach (var flow in Model.Flows)
                {
                    <div class="col-md-4 m-2">
                        <div class="card">
                            <div class="card-body d-flex flex-column">
                                <div class="d-flex justify-content-between">
                                    <h5 class="card-title">@flow.FlowName</h5>
                                </div>
                                <p class="card-text">@flow.FlowDescription</p>
                                <div class="pt-3 pb-3">
                                     <a class="nav-link fw-bold btn btn-primary me-2 full-width-btn p-2"
                                                                                        asp-controller="ShowNotesForBackoffice"
                                                                                        asp-action="index"
                                                                                        asp-route-flowId="@flow.FlowId">
                                                                                         Notities
                                                                                     </a>
                                </div>
                                
                                <div>
                                    <button class="btn btn-outline-secondary edit-flow-button" data-flow-id="@flow.FlowId" title="Edit Flow">
                                        <i class="bi-pencil"></i>
                                    </button>
                                    <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#confirmation-modal" data-flow-id="@flow.FlowId" title="Delete Flow">
                                        <i class="bi-trash"></i>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div> <!-- Einde van de col-md-9 -->
    </div> <!-- Einde van de row -->
</div> <!-- Einde van de container-fluid -->

<div class="modal fade" id="confirmation-modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-label">Wil je dit zeker verwijderen?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Ben je zeker dat je dit wilt verwijderen?
            </div>
            <div class="modal-footer">
                <form id="delete-form" action="" method="post">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Nee</button>
                    <button id="delete-confirm" type="submit" class="btn btn-danger">Ja</button>
                </form>
            </div>
        </div>
    </div>
</div>

<button type="button" id="add-flow-button" class="rounded-add-button">+</button>

@section Scripts {
    <script id="flow-page-script" src="~/dist/flow_page.entry.js" data-subthemeId="@Model.SubThemeId" data-backofficeId="@Model.MainTheme.Project.BackOfficeId" defer="defer"></script>
}

</body>

PygitalToolWeb/Views/BackOffice/ProjectsView.cshtml
@model PhygitalTool.Domain.Platform.BackOffice

@{
    ViewBag.Title = "title";
}

<body class="animated-background">

<div class="container-fluid">
    <div class="row">

        <!-- Sidebar -->
        <div class="col-md-3 sidebar">
            <!-- User Info -->
            <div class="text-center mt-4">
                @foreach (var manager in Model.Managers)
                {
                    if (manager.UserName == User.Identity?.Name)
                    {
                        <img src="@manager.ImageUrl" alt="Profile Picture" class="rounded-circle img-fluid card-img">
                        <h5>@manager.UserName</h5>
                        <p>@Model.Name</p>
                    }
                }
            </div>

            <div class="nav flex-column">
                <a class="nav-link active" asp-area="" asp-controller="BackOffice"
                   asp-action="index">
                    Projecten <span class="badge badge-primary ">@Model.Projects.Count</span>
                </a>
                <a href="#" class="nav-link pt-0">Begeleiders</a>
                <a class="nav-link"
                                   asp-controller="SubTheme"
                                   asp-action="ShowSubThemeSelection"
                                   asp-route-backOfficeId="@Model.BackOfficeId">
                                    Kiosk Modus
                                </a>
                <a class="nav-link pt-0" asp-area="" asp-controller="Home"asp-action="index">Terug</a>
                <a href="/Identity/Account/Logout" class="nav-link">Afmelden</a>
            </div>
        </div>

        <!-- Projects -->
        <div class="col-md-9 main-container" id="projects-container" backoffice-id="@Model.BackOfficeId">
            <h2 class="mt-4">Projecten</h2>
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="toggle-show-projects">
                <label class="form-check-label" for="toggle-show-projects">Toon enkel actieve projecten</label>
            </div>

            <div class="row">
                @foreach (var project in Model.Projects)
                {
                    <div class="col-md-4 m-2">
                        <div class="card clickable" data-project-id="@project.ProjectId" data-href="@Url.Action("Index", "Projects", new { projectId = project.ProjectId })">
                            <div class="card-body d-flex flex-column">
                                <div class="d-flex justify-content-between">
                                    <h5 class="card-title">@project.ProjectName</h5>
                                </div>
                                <p class="card-text">@project.Description</p>
                                <div class="mt-auto">
                                    <div class="d-flex align-items-center">
                                        <span class="badge  project-status">@project.Status</span>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between pt-3">
                                    <div>
                                        <button class="btn btn-outline-secondary edit-project-button btn-sm" data-project-id="@project.ProjectId" title="Edit Project">
                                            <i class="bi-pencil"></i>
                                        </button>
                                        <button class="btn btn-outline-danger remove-project-button btn-sm" data-bs-toggle="modal" data-bs-target="#confirmation-modal" data-project-id="@project.ProjectId" title="Delete Project">
                                            <i class="bi-trash"></i>
                                        </button>
                                    </div>
                                    <button type="button" class="clickable btn btn-light results-btn" data-flow-id="@project.ProjectId" data-href="@Url.Action("Index", "Results", new { projectId = project.ProjectId })">Results</button>
                                </div>
                                <div class="d-flex align-items-center pt-3">
                                    <a class="btn btn-primary me-2 full-width-btn " asp-area="" asp-controller="Projects" asp-action="Index" asp-route-projectid="@project.ProjectId">Bekijk thema's</a>
                                </div>
                            </div>

                        </div>
                    </div>
                }
            </div>
        </div>


        <div class="modal fade" id="confirmation-modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal-label">Wil je dit zeker verwijderen?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Ben je zeker dat je dit wilt verwijderen?
                    </div>
                    <div class="modal-footer">
                        <form id="delete-form" action="" method="post">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Nee</button>
                            <button id="delete-confirm" type="submit" class="btn btn-danger">Ja</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <button type="button" id="add-project-button" class="rounded-add-button">+</button>


    </div>
</div>

@section Scripts {
    <script id="backoffice-script" src="~/dist/backoffice.entry.js" defer="defer" data-backoffice-id="@Model.BackOfficeId"></script>
    <script id="notes-script" src="~/dist/notes.entry.js" defer="defer" data-backoffice-id="@Model.BackOfficeId"></script>
}

</body>

PygitalToolWeb/Views/BackOffice/ResultsView.cshtml
@model PhygitalTool.Domain.Projects.Project

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="results-container">
    <div class="d-flex justify-content-between align-items-center">
        <h2>Resultaten voor @Model.ProjectName</h2>
        <div>
            <a href="#export-button-xls" id="export-nav" class="btn btn-primary">Export</a>
            <a asp-controller="BackOffice" asp-action="index" class="btn btn-primary">BackOffice</a>
        </div>
    </div>
    <div id="results-information-container" data-project-id="@Model.ProjectId"></div>
    <div id="results-container" data-project-id="@Model.ProjectId"></div>
</div>

@section Scripts
{
    <script id="results-page-script" src="~/dist/results.entry.js" defer="defer"></script>
}