PygitalToolWeb/Controllers/BackOffice/SubThemeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.Domain.Projects;

namespace PhygitalTool.Web.Controllers.BackOffice;

public class SubThemeController : Controller
{
    private readonly IProjectManager _projectManager;

    public SubThemeController(IProjectManager projectManager)
    {
        _projectManager = projectManager;
    }

    // GET
    [Authorize(Roles = "Manager")]
    public IActionResult Index(int subThemeId)
    {
        SubTheme subTheme = _projectManager.GetSubTheme(subThemeId);
        return View("~/Views/BackOffice/FlowsView.cshtml", subTheme);
    }
}

PygitalToolWeb/Controllers/Flows/CircularFlowController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using PhygitalTool.BL.Flows;
using PhygitalTool.Domain.FlowPackage;

namespace PhygitalTool.Web.Controllers.Flows;

public class CircularFlowController : Controller
{
    private readonly IFlowManager _flowManager;
    private readonly IHubContext<QuestionHub> _hubContext;


    public CircularFlowController(IFlowManager flowManager, IHubContext<QuestionHub> hubContext)
    {
        _flowManager = flowManager;
        _hubContext = hubContext;
    }

    // Launches a Flow after a user/supervisor selects it. Returns a SubThemView to select the subtheme.
    // GET
    public IActionResult StartFLow(int flowId)
    {
        Flow flow = _flowManager.GetFlow(flowId);
        return View("~/Views/SubTheme/SubThemeInformationBeginView.cshtml", flow);
    }

    // Returns the first question view of a flow after a user/supervisor selects the subtheme.
    public IActionResult GetFirstQuestion(int flowId, int subThemeId)
    {
        Question question = _flowManager.GetFirstFlowQuestion(flowId);
        TempData["subThemeId"] = subThemeId;
        return View("~/Views/LinearFlow/QuestionView.cshtml", question);
    }

    // Returns the view of the next question after the timer has ran out on the previous one.
    // Shows the subtheme information view after each x-amount of questions.
    public IActionResult GetNextQuestion(int flowId, int questionId, int subThemeId)
    {
        int x = 3;

     
        int questionCount = HttpContext.Session.GetInt32("QuestionCount") ?? 0;
        questionCount++;
        HttpContext.Session.SetInt32("QuestionCount", questionCount);

      
        Question nextQuestion = _flowManager.GetNextQuestionInFlow(flowId, questionId);

        if (nextQuestion == null)
        {
            Question question = _flowManager.GetFirstFlowQuestion(flowId);
            TempData["subThemeId"] = subThemeId;
            return View("~/Views/LinearFlow/QuestionView.cshtml", question);
        }


        if (questionCount == x)
        {
         
            HttpContext.Session.SetInt32("QuestionCount", 0);
            var flow = _flowManager.GetFlow(flowId);
            TempData["questionId"] = questionId;
            return View("~/Views/SubTheme/SubThemeInformationCircularView.cshtml", flow);
        }
        
        TempData["subThemeId"] = subThemeId;
        return View("~/Views/LinearFlow/QuestionView.cshtml", nextQuestion);
    }
    
    // Stops the flow when the "stop" button is pressed.
    public IActionResult EndFlow(int flowId)
    {
        Flow flow = _flowManager.GetFlow(flowId);
        return View("CircularFlowEndView", flow);
    }
    
    [HttpPost]
    public async Task<IActionResult> StartFlow()
    {
        await _hubContext.Clients.All.SendAsync("FlowStarted");
        return Ok();
    }
}

PygitalToolWeb/Controllers/Flows/LinearFlowController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using PhygitalTool.BL.Flows;
using PhygitalTool.Domain.FlowPackage;

namespace PhygitalTool.Web.Controllers.Flows;

public class LinearFlowController : Controller
{
    private readonly  IHubContext<QuestionHub> _questionHub;
    private readonly IFlowManager _flowManager;

    public LinearFlowController(IHubContext<QuestionHub> questionHub,IFlowManager flowManager)
    {
        _questionHub = questionHub;
        _flowManager = flowManager;
    }

    // Launches a flow using the flowId, this action is called after the user/supervisor selects the flow.
    // Returns SubThemeView for the user/supervisor to select the subtheme.
    // GET
    public IActionResult StartFLow(int flowId)
    {
        Flow flow = _flowManager.GetFlow(flowId);
        return View("~/Views/SubTheme/SubThemeInformationBeginView.cshtml",flow);
    }

    // Launches the first question of a flow, using the GetFirstFlowQuestion method
    public IActionResult GetFirstQuestion(int flowId)
    {
        Question question = _flowManager.GetFirstFlowQuestion(flowId);
        return View("QuestionView", question);
    }
  

    // Returns the View of the next question after the user submitted the last one.
    public Task<IActionResult> GetNextQuestion(int flowId , int questionId)
    {
        Question nextQuestion = _flowManager.GetNextQuestionInFlow(flowId, questionId);
        if (nextQuestion == null)
        {
            Flow flow = _flowManager.GetFlow(flowId);
            return Task.FromResult<IActionResult>(View("FlowEndView", flow ));
        }
        return Task.FromResult<IActionResult>(View("QuestionView",nextQuestion ));
    }
    
    
    public async Task UpdateCurrentQuestion(Question question)
    {
        await _questionHub.Clients.All.SendAsync("UpdateCurrentQuestion", question);
    }
    
}

PygitalToolWeb/Controllers/Flows/SubThemeController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL.BackOffice;
using PhygitalTool.BL.Flows;
using PhygitalTool.Domain.FlowPackage;

namespace PhygitalTool.Web.Controllers.Flows;

public class SubThemeController : Controller
{
    private readonly IFlowManager _flowManager;
    private readonly IBackOfficeManager _backOfficeManager;

    public SubThemeController(IFlowManager iFlowManager, IBackOfficeManager backOfficeManager)
    {
        _flowManager = iFlowManager;
        _backOfficeManager = backOfficeManager;
    }

    // Returns the information view after a user/supervisor selects a subtheme
    public IActionResult ShowSubThemeInformation(int flowId)
    {
        Flow flow = _flowManager.GetFlow(flowId);
        return View("SubThemeInformationBeginView", flow);
    }

    public IActionResult ShowSubThemeSelection(int backOfficeId )
    {
        var mainTheme = _backOfficeManager.GetBackOfficeWithProjectsAndStuff (backOfficeId);
        return View("SubThemeSelectionView", mainTheme);
    }
}

PygitalToolWeb/Controllers/Util/QrCodeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCoder;

namespace PhygitalTool.Web.Controllers.Util;

public class QrCodeController : Controller
{
    // Generates a QR code for the given link.
    [HttpGet] 
    public IActionResult Generate(string data)
    {
        using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
        {
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q);
            using (BitmapByteQRCode qrCode = new BitmapByteQRCode(qrCodeData))
            {
                byte[] qrCodeImage = qrCode.GetGraphic(20);
               
                return File(qrCodeImage, "image/png");
            }
        }
    }
}

PygitalToolWeb/Views/SubTheme/SubThemeInformationBeginView.cshtml
@using PhygitalTool.Domain.Util
@using Microsoft.Extensions.Localization
@using PhygitalTool.Web.Resources
@model PhygitalTool.Domain.FlowPackage.Flow
@inject IStringLocalizer<ResourcesFlow> Localizer

@{
    var culture = Model.Language switch
    {
        Language.Dutch => "nl",
        Language.French => "fr",
        Language.German => "de",
        _ => "en"
        };
    System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo(culture);
    System.Globalization.CultureInfo.CurrentUICulture = new System.Globalization.CultureInfo(culture);
}

<div class="container-information-view">
<div class="row">
    <div class="sidebar-container col-md-2 p-4">
        
        <img src="@Model.FlowImage" alt="Placeholder afbeelding" class="qr-code">
        <h3 class="pt-3">@Localizer[ResourcesFlow.InterestHeading]</h3>
        <p>@Localizer[ResourcesFlow.IntrestDescription]</p>
        @{
            var scheme = Context.Request.Scheme;
            var host = Context.Request.Host.ToString();
            var actionPath = Url.Action("Index", "ContactInformation", new { id = Model.FlowId });

            var fullUrl = $"{scheme}://{host}{actionPath}";
        }

        <img class="qr-code pt-3" src="@Url.Action("Generate", "QrCode", new { data = fullUrl })" alt="QR Code" style="width:500px; height:500px;"/>
    </div>
    <div class="information-container col-md-10 p-5">


        <h2>@Model.SubTheme.SubThemeName</h2>

        <p>@Model.SubTheme.SubThemeInformation</p>


        @if (Model.FlowType == FlowType.Linear)
        {
            <a class="btn btn-primary submit-button mt-3" asp-area="" asp-controller="LinearFlow"
               asp-action="GetFirstQuestion" asp-route-flowId="@Model.FlowId">
                Start
            </a>
        }
        @if (Model.FlowType == FlowType.Circular)
        {
            <a class="nav-link text-dark" id="submit-button" asp-area="" asp-controller="CircularFlow"
               asp-action="GetFirstQuestion"
               asp-route-flowId="@Model.FlowId"
               asp-route-subThemeId="@Model.SubTheme.SubThemeId">
            </a>
        }

        @if (Model.FlowType == FlowType.Circular)
        {
            <p id="circular-timer"></p>
            <a class="nav-link text-dark" asp-area="" asp-controller="CircularFlow" asp-action="EndFlow" asp-route-flowId="@Model.FlowId">STOP</a>
        }
    </div>
</div>
</div>

@section Scripts {
    <script id="question-page-script" src="~/dist/questions_page.entry.js" data-flowtype="@Model.FlowType.ToString().ToLower()" defer="defer" ></script>
}

PygitalToolWeb/Views/SubTheme/SubThemeInformationCircularView.cshtml
@using PhygitalTool.Domain.Util
@model PhygitalTool.Domain.FlowPackage.Flow

<h2>@Model.SubTheme.SubThemeName</h2>

<p>@Model.SubTheme.SubThemeInformation</p>


<a class="nav-link text-dark" id="submit-button"
   asp-area=""
   asp-controller="CircularFlow"
   asp-action="GetNextQuestion"
   asp-route-flowId="@Model.FlowId"
   asp-route-questionId="@TempData["questionId"]"
   asp-route-subThemeId="@Model.SubTheme.SubThemeId">
</a>

@if (Model.FlowType == FlowType.Circular)
{
    <p id="circular-timer"></p>
    <a class="nav-link text-dark" asp-area="" asp-controller="CircularFlow" asp-action="EndFlow" asp-route-flowId="@Model.FlowId">STOP</a>
}


@{
    var scheme = Context.Request.Scheme;
    var host = Context.Request.Host.ToString(); 
    var actionPath = Url.Action("Index", "ContactInformation", new { id = Model.FlowId});

    var fullUrl = $"{scheme}://{host}{actionPath}";
}
<img src="@Url.Action("Generate", "QrCode", new { data = fullUrl, width = 500, height = 500 })" alt="QR Code"  />


@section Scripts {
    <script id="question-page-script" src="~/dist/questions_page.entry.js" data-flowtype="@Model.FlowType.ToString().ToLower()" defer="defer" ></script>
}

PygitalToolWeb/Views/SubTheme/SubThemeInformationView.cshtml
@using Domain.Domain.Util
@model Domain.FlowPackage.FlowSubTheme

<h2>@Model.SubTheme.SubThemeName</h2>

<p>@Model.SubTheme.SubThemeInformation</p>

@if (Model.Flow.FlowType == FlowType.Linear)
{
    <a class="nav-link text-dark" asp-area="" asp-controller="LiniareFlow"
       asp-action="GetFirstQuestion" asp-route-flowId="@Model.Flow.FlowId">
        Start
    </a>
}
@if (Model.Flow.FlowType == FlowType.Circular)
{
    <a class="nav-link text-dark" id="submitButton" asp-area="" asp-controller="CircularFlow"
       asp-action="GetFirstQuestion"
       asp-route-flowId="@Model.Flow.FlowId"
       asp-route-subThemeId="@Model.SubTheme.SubThemeId">
    </a>
}

@if (Model.Flow.FlowType == FlowType.Circular)
{
    <p id="circular-timer"></p>
    <a class="nav-link text-dark" asp-area="" asp-controller="CircularFlow" asp-action="EndFlow" asp-route-flowId="@Model.Flow.FlowId">STOP</a>
}

@section Scripts {
    <script src="~/dist/circularFlow.entry.js"></script>
}

PygitalToolWeb/Views/SubTheme/SubThemeSelectionView.cshtml
@using PhygitalTool.Domain.Util
@using Microsoft.IdentityModel.Tokens
@model PhygitalTool.Domain.Platform.BackOffice

@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<body class="animated-background">
<h2>Kies een thema:</h2>
@foreach (var project in Model.Projects)
{
    @foreach (var maintheme in project.MainThemes)
    {
        <h3>@maintheme.ThemeName</h3>

        @foreach (var subtheme in maintheme.SubThemes)
        {
            {
                <div class="row">
                    <div class="col-md-4 m-2">
                        <div class="card p-3">
                            <h4>@subtheme.SubThemeName :</h4>
                            @foreach (var flow in subtheme.Flows)
                            {
                                if (!flow.Questions.IsNullOrEmpty())
                                {
                                    var controller = flow.FlowType == FlowType.Linear ? "LinearFlow" : "CircularFlow";
                                    var action = "StartFlow";
                                    var flowTypeName = flow.FlowType == FlowType.Linear ? "Linear" : "Circulair";

                                    <a class="btn btn-primary me-2 full-width-btn mt-3" asp-area=""
                                       asp-controller="@controller"
                                       asp-action="@action"
                                       asp-route-flowId="@flow.FlowId">
                                        @flow.FlowName (@flowTypeName)
                                    </a>
                                }
                            }
                        </div>
                    </div>
                </div>
            }
        }
    }
}

</body>