PygitalToolWeb/Controllers/Flows/ContactInformationController.cs
using Microsoft.AspNetCore.Mvc;
using PhygitalTool.BL;
using PhygitalTool.BL.Flows;
using PhygitalTool.Domain.FlowPackage;
using PhygitalTool.Web.Controllers.Flows;

namespace PhygitalTool.Web.Controllers;

public class ContactInformationController : Controller
{
    
    private readonly IFlowManager _flowManager;
    private readonly ILogger<QuestionController> _logger;
    private readonly UnitOfWork _unitOfWork;
    
    public ContactInformationController(IFlowManager flowManager, ILogger<QuestionController> logger, UnitOfWork unitOfWork)
    {
        _flowManager = flowManager;
        _logger = logger;
        _unitOfWork = unitOfWork;
    }
    
    // GET
    public IActionResult Index(int id)
    {
        var contactInfoStart = new ContactInformation(_flowManager.GetFlow(id));
        return View("index", contactInfoStart);
    }
    
 
    [HttpPost]
    public IActionResult Contact(ContactInformation contactInformation, Dictionary<int, string> answers)
    {
        
        foreach (var answer in answers)
        {
            _flowManager.AddUserAnswer(answer.Value, contactInformation.FlowId, answer.Key);
        }
        
        if(ModelState.IsValid)
        {
            _unitOfWork.BeginTransaction();
            _flowManager.SaveContactInformation(contactInformation);
            _unitOfWork.Commit();
            return RedirectToAction("Index", "Home"); 
        }
  
        contactInformation.Flow = _flowManager.GetFlow(contactInformation.FlowId);

        return View("Index", contactInformation);
        
        
    }
}

PygitalToolWeb/Views/ContactInformation/index.cshtml
@using PhygitalTool.Domain.Util
@model PhygitalTool.Domain.FlowPackage.ContactInformation

@{
    ViewBag.Title = "Contact information";
    Layout = "_Layout";
}
<body class="background-contract-form">
    <h2>Laat je contactgegevens achter en blijf op de hoogte over info rond dit thema</h2>

    <form asp-controller="ContactInformation" asp-action="Contact" method="post">

        <div class="mb-3">
            <label asp-for="Email" class="form-label">Email</label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Name" class="form-label">Naam</label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Birthdate" class="form-label">GeboorteDatum</label>
            <input asp-for="Birthdate" class="form-control" type="date"/>
            <span asp-validation-for="Birthdate" class="text-danger"></span>
        </div>

        <input asp-for="FlowId" type="hidden"/>

        @foreach (var question in Model.Flow.Questions)
        {
            if (question.QuestionType == QuestionType.Open)
            {
                <div class="mb-3">
                    <label class="form-label">@question.QuestionText</label>
                    <input type="text" name="answers[@question.QuestionId]" class="form-control"/>
                    <span class="text-danger"></span>
                    <input type="hidden" name="currentFlow" value="@question.FlowId"/>
                    <input type="hidden" name="currentQuestion" value="@question.QuestionId"/>
                    <input type="hidden" name="subThemeId" value="@question.Flow.SubThemeId"/>
                </div>
            }
        }

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>